<table>
<tr>
<td>user_group_id</td>
<td><?=$qryVResult['user_group_id']?></td>
</tr>
<tr>
<td>user_type</td>
<td><?=$qryVResult['user_type']?></td>
</tr>
<tr>
<td>user_real_name</td>
<td><?=$qryVResult['user_real_name']?></td>
</tr>
<tr>
<td>user_tel</td>
<td><?=$qryVResult['user_tel']?></td>
</tr>
<tr>
<td>user_email</td>
<td><?=$qryVResult['user_email']?></td>
</tr>
<tr>
<td>user_account</td>
<td><?=$qryVResult['user_account']?></td>
</tr>
<tr>
<td>user_password</td>
<td><?=$qryVResult['user_password']?></td>
</tr>
<tr>
<td>status</td>
<td><?=$qryVResult['status']?></td>
</tr>
<tr>
<td>flag</td>
<td><?=$qryVResult['flag']?></td>
</tr>
<tr>
<td>created</td>
<td><?=$qryVResult['created']?></td>
</tr>
<tr>
<td>modified</td>
<td><?=$qryVResult['modified']?></td>
</tr>
</table>