<table>
<tr>
<td>sk_name</td>
<td><?=$qryVResult['sk_name']?></td>
</tr>
<tr>
<td>sk_order</td>
<td><?=$qryVResult['sk_order']?></td>
</tr>
<tr>
<td>flag</td>
<td><?=$qryVResult['flag']?></td>
</tr>
<tr>
<td>user_id</td>
<td><?=$qryVResult['user_id']?></td>
</tr>
<tr>
<td>created</td>
<td><?=$qryVResult['created']?></td>
</tr>
<tr>
<td>modified</td>
<td><?=$qryVResult['modified']?></td>
</tr>
</table>